language: node_js
services:
- postgresql
env:
- NODE_ENV=test
before_script:
- sudo -u postgres createuser -s foodcomputer
- npm install -g sequelize-cli
- sequelize db:create
- sequelize db:migrate
- cd front-end && npm install && cd ..
script:
- npm run lintAll
- npm run testAll
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - http://requestbin.fullcontact.com/1mkbp4i1
      - https://foodcomputer.io:9000/hooks/deploy
    on_success: always # default: always
    on_failure: never # default: always
    on_start: never   # default: never
    on_cancel: never # default: always
    on_error: never # default: always
