language: node_js
services:
- postgresql
env:
- NODE_ENV=test
before_script:
- sudo -u postgres createuser -s foodcomputer
- npm install -g sequelize-cli
- sequelize db:create
- sequelize db:migrate
script:
- npm run lint
- npm test
